### ISSUE TITLE
Hyperlinks are too light

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#10]
Probably using the default colour scheme for 'functional' elements, but in the context of text on a white background there is actually very little contrast, making the text difficult to read. I'm happy to keep the blue, but could it be slightly darker in this context?

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hyperlinks are too light](https://trello.com/c/qPW49gDH/238-hyperlinks-are-too-light)
