### ISSUE TITLE
Select needs a multiple-select (list) option

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#12]
There are cases (arguably few) where we might want to show a tall list of options from which people can select multiple items. It would be good to have it styled consistently with the rest of the form elements.

A potential counter-argument is that from a UX perspective CTRL-clicking items in that sort of list is unintuitive, and better alternatives exist. If that's the case, maybe we need to provide an alternative component specially for this case.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Select needs a multiple-select (list) option](https://trello.com/c/jZGvkiho/215-select-needs-a-multiple-select-list-option)
