### ISSUE TITLE
Scroll bars appearing on tab bar and table container

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#14]
In Chrome, IE and Firefox, a disabled scrollbar appears when it probably shouldn't.

![image](https://user-images.githubusercontent.com/11058659/26929743-ac76dba6-4c52-11e7-9f1d-7b2319ae11dc.png)

![image](https://user-images.githubusercontent.com/11058659/26929755-b97e5130-4c52-11e7-87dd-8918ee6d3d72.png)

**Comment by stephen9001** [comment]
Can you please confirm if this was on a Windows machine; and which version of Windows and of the browsers the error was occurring on? @mdcrown

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scroll bars appearing on tab bar and table container](https://trello.com/c/Bvv4vbpa/237-scroll-bars-appearing-on-tab-bar-and-table-container)
