### ISSUE TITLE
Significant lists need to show hierarchy

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#16]
There are cases, such as sidebar navigation, where it would be useful to show hierarchy (parents and children). If this is already implemented, it's not demonstrated in the style guide yet.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Significant lists need to show hierarchy](https://trello.com/c/WckudbD5/235-significant-lists-need-to-show-hierarchy)

**Comment by stephen9001** [comment]
Hierarchy now shown
