### ISSUE TITLE
Need some guidance on site navigation

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#17]
I wouldn't call it a component, but it should be either a feature or a recommended best practice. Site navigation is a core part of any site's UX, and there is a lot of variation in implementation across RC. I know Campus has previously championed the use of a mega-menu; personally, I think that's fine for a massive ecommerce site like Amazon but overkill for a Royal Canin brand site. It should definitely be up to the individual subsidiary what goes into the menu, but I think it's important that there is some consistency in the way it looks and works, ideally backed up with some best practice research.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need some guidance on site navigation](https://trello.com/c/ENx3CFC4/234-need-some-guidance-on-site-navigation)

**Comment by stephen9001** [comment]
Previously created an issue for this so closing this.
