### ISSUE TITLE
Maps with RC branding

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#18]
Can we (should we?) style the maps to be more in keeping with the rest of our branding? For example, on the Royal Family website (e.g. https://royalfamily.royalcanin.co.uk/breed/896283194/labrador-retriever-facts) the map itself is black and white, with customised red controls.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maps with RC branding](https://trello.com/c/mWH4ncgR/233-maps-with-rc-branding)
