### ISSUE TITLE
Maps need customisable marker icons

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#19]
The implementation in the style guide only gives the option of one marker style. In some markets there is a need for a whole range of different icons depending on the status or segmentation of the partners. For example, we would definitely want to differentiate between shops and vets. There may also be cases where we'd want to highlight other types of partner (e.g. breeders, groomers) or additional features or statuses for partners (e.g. Loyalty stores, trained, certified). We may not be able to provide all those icons out of the box, but it would be good if each market could specify a local image they want to use for each marker.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maps need customisable marker icons](https://trello.com/c/WcLPD8YD/232-maps-need-customisable-marker-icons)
