### ISSUE TITLE
UI/UX best practices in style guide

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#21]
I would love to see an additional area in the style guide containing advice and best practice relating to page layout and template structure, not to prescribe how people should implement the WDL but to guide people in a direction that is sensible. https://www.goodui.org is a good point of reference, although there are some areas of layout that are missed out there. Perhaps we can suggest some good (effective) layouts for the following as a starting point:

- Navigation (primary and secondary)
- Site header and footer
- Login / register forms
- Profile management
- Article lists
- Search results
- Product taxonomy (ranges)
- Product pages

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI/UX best practices in style guide](https://trello.com/c/OplAPd06/230-ui-ux-best-practices-in-style-guide)
