### ISSUE TITLE
Provide static resources on CDN

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#22]
Some developers may indeed want to clone the repo and build it themselves, but for most projects all we want is to provide the compiled output. It would seem ideal to provide this on a central CDN, if possible. We would just need to be careful about providing each version, so that new releases don't have to be immediately adopted - live sites using old versions should be able to continue using the version of the WDL they've been built with so they don't break.

I would suggest we offer the compiled CSS and JS, logo images (so subsidiaries can't mess around with it), icons and fonts.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define CDN deployment](https://trello.com/c/kau17MJB/138-define-cdn-deployment)
