### ISSUE TITLE
Form labels overlap the element above

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#24]
I'm playing around with creating a simple login form, and I notice that when the input is selected the label moves up and over the element above, making it hard to read.

```
<h2>Log in</h2>
<form action="#">
  <span class="rc-input">
    <input type="email" id="email">
    <label for="email"><span class="rc-label">Email address</span></label>
  </span>
  <span class="rc-input">
    <input type="password" id="password">
    <label for="password"><span class="rc-label">Password</span></label>
  </span>
  <p><button>Log in</button> <button class="button--secondary" href="#forgot-password">Forgotten your password?</button></p>
</form>
```

![image 525](https://user-images.githubusercontent.com/11058659/27380909-dcfb4a2a-5678-11e7-975d-c88c28c2b8b6.png)
![image 526](https://user-images.githubusercontent.com/11058659/27380914-df45b1ee-5678-11e7-9461-59f5d04ebf68.png)

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Form labels overlap the element above](https://trello.com/c/Eg3TWHQD/201-form-labels-overlap-the-element-above)
