### ISSUE TITLE
Remove jquery

### ISSUE THREAD

**Issue by danharper83** [First10/royal-canin-design-language#27]
### Brief title
Remove jQuery dependency.

### Description of desired feature
Rewrite carousel to use vanilla JS not jQuery

### Why the feature is needed
This will make the styleguide much more future proof

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove dependencies on jQuery](https://trello.com/c/ssFHyKye/213-remove-dependencies-on-jquery)
