### ISSUE TITLE
Split the portal from the assets

### ISSUE THREAD

**Issue by danharper83** [First10/royal-canin-design-language#28]
### Brief title
Remove portal from assets

### Description of desired feature
Remove the assets from the code 

### Why the feature is needed
It makes it simpler to deploy and manage the two things independently, we will need another repo to host the portal in.

**Comment by danharper83** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split portal and implementation](https://trello.com/c/34gphDtS/133-split-portal-and-implementation)

**Comment by danharper83** [comment]
Do I need to update the DNS settings?

Also can we just use the repo root now and not use the process of pushing a subtree?

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split the portal from the assets](https://trello.com/c/rdMPj1Kg/200-split-the-portal-from-the-assets)
