### ISSUE TITLE
BEMs implantation class clear-up

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#29]
### BEMs implantation class clear-up
Classes need refining into BEMs style formatting with clear inheritance patterns.

### Description of the desired feature
Reduction of classes required for implementing a feature/style/layout.

### Why the feature is needed
Performance and maintainability.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BEMs implantation class clear-up](https://trello.com/c/DkCIZqwU/199-bems-implantation-class-clear-up)
