### ISSUE TITLE
Variables as sass maps

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#30]
### Sass variables need to be namespaced with appropriate required functions
Give the new feature a name.

### Variables grouping
Variables will be logically grouped with a utility function for easy access.

### Why the feature is needed
Better maintainability and organisation.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variables as sass maps](https://trello.com/c/lHMfu0Mv/198-variables-as-sass-maps)

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variables as sass maps](https://trello.com/c/lHMfu0Mv/198-variables-as-sass-maps)
