### ISSUE TITLE
Typographic naming

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#31]
### Typographic styles should have names
Abstraction of typographic styles into named classes/variables.

### Conversion to sass maps with function
Sass map with names and attributes with a function for users.

### Why the feature is needed
Namespacing, maintainability and ease of use.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Typographic naming](https://trello.com/c/jwz8RGbG/197-typographic-naming)
