### ISSUE TITLE
Strip any layout form components

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#32]
### Strip any layout form components
Removal of any layout in components as this should be inherited from its wrapper etc.

### Why we need this
Increased predictability between component and layout.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Strip any layout form components](https://trello.com/c/wgxhAS0L/195-strip-any-layout-form-components)
