### ISSUE TITLE
Breakpoint encapsulation

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#33]
### Breakpoint encapsulation
Breakpoints should encapsulation and referenced throughout.

### Description of the desired feature
Breakpoints will be in sass map then reference with a function.

### Why the feature is needed
Maintainability and consistency.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Breakpoint encapsulation](https://trello.com/c/M8x7MrLm/216-breakpoint-encapsulation)
