### ISSUE TITLE
Layout utilities

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#34]
### Brief title
The addition of layout utilities.
IE for:
* Max widths
* Grid layouts
* Layout patterns
* Padding
* Margin

### Description of the desired feature
Utility classes, mixins and functions.

### Why the feature is needed
Maintainability and consistency.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Layout utilities](https://trello.com/c/QbkEyQ1G/202-layout-utilities)
