### ISSUE TITLE
Logo implementation

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#37]
### Logo implementation
Logo implementation documentation

**Comment by jmdrawneek** [comment]
We need to chat about how we're going to implement this.

@danharper83 @stephen9001

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix logo layouts on logos page](https://trello.com/c/vwZCAhZQ/185-fix-logo-layouts-on-logos-page)
