### ISSUE TITLE
Colours implementation

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#38]
### Colours implementation
Colours implementation documentation.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colours implementation](https://trello.com/c/enNf88PM/229-colours-implementation)

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colours implementation](https://trello.com/c/enNf88PM/229-colours-implementation)
