### ISSUE TITLE
Headings tidy up

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#40]
### Headings tidy up

From notes:
Typeface says H tags are Medium but this page says Regular? Which? // Correct to regular
What are Initial Caps? Is it not a css property? Do you mean the typograph term sentence case or capitalise? // Sentence case
Primary Desktop Typography Styles –– What? Where’s mobile etc? // Add mobile column when we have named styles
Headings-modifiers Broken // Remove

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Headings tidyup](https://trello.com/c/uwtipnZN/227-headings-tidyup)
