### ISSUE TITLE
Swap A tags for Buttons and reverse where incorrect usage found

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#42]
### Swap A tags for Buttons and reverse where incorrect usage found
Buttons are for internal page actions.
Anchor tags are for external page link.

These rules should always be followed as it semantically correct.

## Incorrect usage:
* Buttons page
* Progress page
* Interactive page / carosuels / pagers
* Tool tips

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Swap A tags for Buttons and reverse where incorrect usage found](https://trello.com/c/sMu1DwgX/211-swap-a-tags-for-buttons-and-reverse-where-incorrect-usage-found)
