### ISSUE TITLE
Forms documentation / issues

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#44]
###  Forms documentation / issues

Errors found in documentation:
* Error on Positioning Inputs @@
* Reveal password icon not centred
* More @@ in form elements – inputs
* Broken link: Radio buttons page === select page
* Broken link: Options buttons page === select page

Code Issues:
* From validation should be done via http://www.the-art-of-web.com/html/html5-form-validation/

## Form submit button
Doesn't match the other buttons
Should be blue/green

We should consolidate the form inputs and reduce duplication.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Form documentation](https://trello.com/c/5SuQhOz5/209-form-documentation)
