### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#46]
### Icons
Icons should be supplied as assets, not inline code.

Bundle icons into sprites with colours options:
Last solution:
https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images

BEMs classes should be added for implementation 

Icons should be consistently trimmed.

**Comment by jmdrawneek** [comment]
Icon workflow added.

Icons need supplying in the following uniform naming convention as their names become the utility classes.

noun-variant--colour.svg

We still need to add the documentation to the portal.

CC: @danshoreman @stephen9001

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Icons](https://trello.com/c/U2wYI4Mr/192-icons)
