### ISSUE TITLE
Interactive section

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#48]
### Interactive section

- 1. Classes structure needs amending, poor inheritance.
- 2. Modifier used instead of entity in selector
- 3. SVG assets should be used instead of inline svgs

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Interactive section](https://trello.com/c/9PQk4D8V/191-interactive-section)
