### ISSUE TITLE
Social Icons

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#51]
### Social Icons
Should be asset SVGs not inline.

**Comment by jmdrawneek** [comment]
Waiting on assets.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix logo layouts on logos page](https://trello.com/c/vwZCAhZQ/185-fix-logo-layouts-on-logos-page)

**Comment by danshoreman** [comment]
@jmdrawneek all icons created in the following folder https://www.dropbox.com/sh/wv7yb99zj6rwhzc/AADC-yxli_cUvGGDf6i-EiTda?dl=0
The cat and dog icons need to be reviewed so I've not included them until they're signed off.
