### ISSUE TITLE
Carousels & Image Galleries

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#52]
### Carousels & Image Galleries
Documentation needs javascript implementation examples and any examples.
ARIAs needs adding with supporting javascript.
Pager and next/previous should be button elements not A tags.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Carousels & image galleries](https://trello.com/c/ImrZxast/205-carousels-image-galleries)
