### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#54]
### Grid
Reduction of possible column widths.

The inclusion of use cases and utility classes/placeholders for fast setup.

Examples of markup and implementation.

**Comment by jmdrawneek** [comment]
Waiting on discussions / use cases from @danshoreman

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write page to explain use cases for wrappers and grids](https://trello.com/c/c9c1andG/173-write-page-to-explain-use-cases-for-wrappers-and-grids)
