### ISSUE TITLE
Progress js needs refactoring

### ISSUE THREAD

**Issue by jmdrawneek** [First10/royal-canin-design-language#58]
## Progress bar js needs refactoring
Currently, the progress bar javascript pollutes the global scope, uses jQuery and could do with better structuring.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Progress js needs refactoring](https://trello.com/c/fFnZHHmd/225-progress-js-needs-refactoring)
