### ISSUE TITLE
Add a small footer with a Ts&Cs link

### ISSUE THREAD

**Issue by stephen9001** [First10/royal-canin-design-language#69]
### Brief title
Add a footer. put a link to a new page in the footer that will contain the Ts&Cs

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add footer for T&C and copyright](https://trello.com/c/3dZdBxGu/180-add-footer-for-tc-and-copyright)

**Comment by jmdrawneek** [comment]
@stephen9001 Do we have copy for this page? Should probably add a note about the type usage!

**Comment by stephen9001** [comment]
@jmdrawneek requested info from Rick F

**Comment by stephen9001** [comment]
@jmdrawneek not currently, please just create a standard format Ts&Cs page which is accessible from a link in small footer; absolutely need to include info on type... but we should also include that on the fonts page of the portal as well
