### ISSUE TITLE
There should be more size consistency between the buttons on the mobile break-point.

### ISSUE THREAD

**Issue by stephen9001** [First10/royal-canin-design-language#70]

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Buttons | fix multiple variations of buttons on 'Icon Button', 'Functional Button' pages.](https://trello.com/c/ggfURaXX/160-buttons-fix-multiple-variations-of-buttons-on-icon-button-functional-button-pages)

**Comment by jmdrawneek** [comment]
@stephen9001 Do we have any more details on this?

**Comment by stephen9001** [comment]
@jmdrawneek requested info from Rick F

**Comment by stephen9001** [comment]
this card is largely referencing two comments I made during the workshops around the error button:

1. Anytime we present a user with an error, we need to use (#C71838). Currently the error button is using (#E2001A), which is our primary color.

2. There should be more size consistency between the buttons on the mobile break-point.

**Comment by jmdrawneek** [comment]
@rf-rc2 Please could elaborate on your second point?
