### ISSUE TITLE
Minor copy change and additions

### ISSUE THREAD

**Issue by stephen9001** [First10/royal-canin-design-language#71]
- Add line on use of typography
- Add guidance on use of shading
- Remove the word 'web' from 'web design language' from all copy
- Refine language to reflect sitecore naming - atoms, elements etc.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Minor copy change and additions](https://trello.com/c/sWMpyZ3H/159-minor-copy-change-and-additions)

**Comment by jmdrawneek** [comment]
@stephen9001 Do we have any more details on these?
