### ISSUE TITLE
SVG'S seem distorted

### ISSUE THREAD

**Issue by danharper83** [First10/royal-canin-design-language#76]
### Expected behaviour
The logos should look crisp.

### Actual behaviour
The logos look jagged and distorted

### I'm seeing this behaviour on
*Operating system*
- [ ] Windows 10
- [ ] Windows 8
- [ ] Windows 7
- [x] OS X
- [ ] Andoid
- [ ] iOS

*Browser*
- [ ] All browsers
- [ ] Edge
- [ ] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Firefox (latest stable version)
- [x] Chrome (latest stable version)
- [ ] Safari

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SVG'S seem distorted](https://trello.com/c/FY2xzZJU/271-svgs-seem-distorted)

**Comment by jmdrawneek** [comment]
@danharper83 Was this on every page? Do you mean icons and/or logos?

**Comment by danharper83** [comment]
It was on every page, it was the logo svg wherever it was being displayed. Seems to have resolved itself on my machine.
