### ISSUE TITLE
Ordered list showing as unordered in style guide

### ISSUE THREAD

**Issue by mdcrown** [First10/royal-canin-design-language#9]
The code says to use `<ol>`, but it appears it's actually rendering the page using `<ul>`. I think this is an issue with the style guide rather than the actual CSS.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [<ol> is displaying as <ul>](https://trello.com/c/LeKM13Pg/214-ol-is-displaying-as-ul)
