### ISSUE TITLE
Logo Icon Font

### ISSUE THREAD

**Issue by mbbillz** [First10/royal-canin-design-language#95]
### Description of desired feature
Take the logo out of SVG sprite sheet and create icon font specifically for the logos. 

### Why the feature is needed
Will improve scalability and rendering issues on older browsers.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Logo icon font](https://trello.com/c/9ubpLiqO/296-logo-icon-font)
